server:
  port: 8001
  servlet:
    context-path: /
spring:
  application:
    name: icom-product-service
    version: 0.1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/productdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  liquibase:
    enabled: true
    contexts: dev #With Spring Boot 2.0, liquibase property is deprecated and moved under spring root: spring.liquibase.contexts
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ICOMMERCE_ONLINE_PROCESSING
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yaml
  dropFirst: false
springdoc:
  packagesToScan: com.icom
icom:
  cart:
    item-created-topic:
      name: ITEM_CREATED_TOPIC5

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:10.1:///product_unittest_table
#  jpa:
#    hibernate:
#      ddl-auto: create # Switch off, all database set up will be covered by liquibase.
  liquibase:
    #If we want to init data inside unitest, you have to turn off liquibase.
    #We can prepare data test and instruct liquibase to automatically update our unit-test data.
    enabled: true
    contexts: unittest
logging:
  level:
    root: WARN
