apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
spec:
  ports:
    - name: "5432port"
      port: 5432
      targetPort: 5432
      protocol: TCP
  type: LoadBalancer
  selector:
    app: postgres