apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/component: deployment
  name: product-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: product-pod
  template:
    metadata:
      namespace: default
      labels:
        name: product-pod
    spec:
      containers:
        - name: product-pod
          envFrom:
            - secretRef:
                name: product-secret
                optional: false
            - configMapRef:
                name: product-config
                optional: false
          image: product-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8001
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8001
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 10
