--liquibase formatted sql
--changeset hungdh:20220825
insert into PRODUCT_CATEGORY(PRODUCT_CATEGORY_NAME, CREATED_AT)
values ('CATEGORY-1', current_timestamp);
insert into PRODUCT_CATEGORY(PRODUCT_CATEGORY_NAME, CREATED_AT)
values ('CATEGORY-2', current_timestamp);
insert into PRODUCT_CATEGORY(PRODUCT_CATEGORY_NAME, CREATED_AT)
values ('CATEGORY-3', current_timestamp);
insert into PRODUCT_CATEGORY(PRODUCT_CATEGORY_NAME, CREATED_AT)
values ('CATEGORY-4', current_timestamp);
insert into PRODUCT_CATEGORY(PRODUCT_CATEGORY_NAME, CREATED_AT)
values ('CATEGORY-5', current_timestamp);
insert into PRODUCT_CATEGORY(PRODUCT_CATEGORY_NAME, CREATED_AT)
values ('CATEGORY-6', current_timestamp);
insert into PRODUCT_CATEGORY(PRODUCT_CATEGORY_NAME, CREATED_AT)
values ('CATEGORY-7', current_timestamp);
insert into PRODUCT_CATEGORY(PRODUCT_CATEGORY_NAME, CREATED_AT)
values ('CATEGORY-8', current_timestamp);
insert into PRODUCT_CATEGORY(PRODUCT_CATEGORY_NAME, CREATED_AT)
values ('CATEGORY-9', current_timestamp);
insert into PRODUCT_CATEGORY(PRODUCT_CATEGORY_NAME, CREATED_AT)
values ('CATEGORY-10', current_timestamp);


insert into PRODUCT(PRODUCT_NAME, PRODUCT_DESCRIPTION, CREATED_AT, PRODUCT_BRANCH, PRODUCT_COLOR, PRODUCT_PRICE,
                    PRODUCT_TOTAL_QUALITY, PRODUCT_REMAIN_QUALITY, PRODUCT_CATEGORY_ID)
values ('PRODUCT-NAME-1', 'PRODUCT DESCRIPTION', current_timestamp, 'branch 1', 'RED', 100.30, 10, 10,
        (select pc.PRODUCT_CATEGORY_ID from PRODUCT_CATEGORY pc where pc.PRODUCT_CATEGORY_NAME = 'CATEGORY-1'));

insert into PRODUCT(PRODUCT_NAME, PRODUCT_DESCRIPTION, CREATED_AT, PRODUCT_BRANCH, PRODUCT_COLOR, PRODUCT_PRICE,
                    PRODUCT_TOTAL_QUALITY, PRODUCT_REMAIN_QUALITY, PRODUCT_CATEGORY_ID)
values ('PRODUCT-NAME-2', 'PRODUCT DESCRIPTION', current_timestamp, 'branch 2', 'RED', 1200.30, 10, 10,
        (select pc.PRODUCT_CATEGORY_ID from PRODUCT_CATEGORY pc where pc.PRODUCT_CATEGORY_NAME = 'CATEGORY-1'));

insert into PRODUCT(PRODUCT_NAME, PRODUCT_DESCRIPTION, CREATED_AT, PRODUCT_BRANCH, PRODUCT_COLOR, PRODUCT_PRICE,
                    PRODUCT_TOTAL_QUALITY, PRODUCT_REMAIN_QUALITY, PRODUCT_CATEGORY_ID)
values ('PRODUCT-NAME-3', 'PRODUCT DESCRIPTION', current_timestamp, 'branch 3', 'ORANGE', 1300.30, 10, 0,
        (select pc.PRODUCT_CATEGORY_ID from PRODUCT_CATEGORY pc where pc.PRODUCT_CATEGORY_NAME = 'CATEGORY-2'));

insert into PRODUCT(PRODUCT_NAME, PRODUCT_DESCRIPTION, CREATED_AT, PRODUCT_BRANCH, PRODUCT_COLOR, PRODUCT_PRICE,
                    PRODUCT_TOTAL_QUALITY, PRODUCT_REMAIN_QUALITY, PRODUCT_CATEGORY_ID)
values ('PRODUCT-NAME-4', 'PRODUCT DESCRIPTION', current_timestamp, 'branch 4', 'ORANGE', 1400.30, 10, 5,
        (select pc.PRODUCT_CATEGORY_ID from PRODUCT_CATEGORY pc where pc.PRODUCT_CATEGORY_NAME = 'CATEGORY-2'));